package com.joybar.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * auto greenDao generate javaBean by joybar
 */
public class Note {

    private Long id;
    /** Not-null value. */
    private String title;
    private String content;
    private String createTime;
    private String addNewColumn;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, String title, String content, String createTime, String addNewColumn) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.createTime = createTime;
        this.addNewColumn = addNewColumn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getAddNewColumn() {
        return addNewColumn;
    }

    public void setAddNewColumn(String addNewColumn) {
        this.addNewColumn = addNewColumn;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        return "Note{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", createTime='" + createTime + '\'' +
                ", addNewColumn='" + addNewColumn + '\'' +
                '}';
    }
    // KEEP METHODS END

}
