package com.joybar.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * auto greenDao generate javaBean by joybar
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String name;
    private String sex;
    private String joinTime;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String name, String sex, String joinTime) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.joinTime = joinTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getJoinTime() {
        return joinTime;
    }

    public void setJoinTime(String joinTime) {
        this.joinTime = joinTime;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", sex='" + sex + '\'' +
                ", joinTime='" + joinTime + '\'' +
                '}';
    }
}
