package com.joybar.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.joybar.db.entity.Note;
import com.joybar.db.entity.User;
import com.joybar.db.entity.Picture;

import com.joybar.db.dao.NoteDao;
import com.joybar.db.dao.UserDao;
import com.joybar.db.dao.PictureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig pictureDaoConfig;

    private final NoteDao noteDao;
    private final UserDao userDao;
    private final PictureDao pictureDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        pictureDao = new PictureDao(pictureDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(User.class, userDao);
        registerDao(Picture.class, pictureDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        pictureDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

}
